### ISSUE TITLE
get_uptime for Windows CE devices raises exception

### ISSUE THREAD

**Issue by jmichiel** [cread/ecks#1]
This is the Exception:
  File "C:\Python26\lib\site-packages\ecks-0.8-py2.6.egg\ecks\plugins\uptime.py", line 43, in get_uptime
    if ("Windows" in os) and (int(re.search("\(Build (\d+) ", os).groups()[0]) < 7600):
AttributeError: 'NoneType' object has no attribute 'groups'

Apparently, on Windows CE the OS description is 'Microsoft Windows CE Version 5.0 (Build 1400)', while for a Windows Server it is 'Hardware: x86 Family 6 Model 23 Stepping 8 AT/AT COMPATIBLE - Software: Windows Version 5.2 (Build 3790 Multiprocessor Free)'

For Win CE, there is no space after the Build number, so the regexp '"\(Build (\d+) " turns up nothing.

**Comment by cread** [comment]
Just realized I didn't close this issue when I fixed it *blush*
